### ISSUE TITLE
deja ingresar <hr> en los comentarios

### ISSUE THREAD

**Issue by danistiven19** [mejialvarez/flowoverstack#2]
Cuando voy a escribir un comentario si escribo "< hr >", muestra una linea horizontal

![hr issue](https://cloud.githubusercontent.com/assets/8224402/15456163/b2a16246-202d-11e6-890b-daaa0dc142bb.PNG)

**Comment by mejialvarez** [comment]
Ese es el comportamiento esperado, cada comentario tiene un borde superior y se ignora el html, por eso aparece vacio.
