### ISSUE TITLE
Markdown no funciona para el título de la pregunta

### ISSUE THREAD

**Issue by danistiven19** [mejialvarez/flowoverstack#8]
Cuando se crea una pregunta y se escribe el título con el formato markdown, en la página de la pregunta y en la página principal se ven los caracteres especiales del Markdown format

![markdown issue 1](https://cloud.githubusercontent.com/assets/8224402/15455634/7d563e9e-201f-11e6-871c-b688b862196c.PNG)
![markdown issue 2](https://cloud.githubusercontent.com/assets/8224402/15455636/7d59fcbe-201f-11e6-9514-51893267bdf3.PNG)
![markdown issue 3](https://cloud.githubusercontent.com/assets/8224402/15455635/7d59aae8-201f-11e6-8f41-9c1a6ee52d0e.PNG)

**Comment by mejialvarez** [comment]
Ese es el comportamiento esperado porque los títulos no tienen habilitado markdown.
